### ISSUE TITLE
error when installing with "pip install cbpi4-http-actor"

### ISSUE THREAD

**Issue by Pumba1970** [hurra/cbpi4-http-actor#1]
ERROR: Cannot install cbpi4-http-actor==0.0.1 and cbpi4-http-actor==0.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    cbpi4-http-actor 0.0.2 depends on cbpi>=4.0.0.34
    cbpi4-http-actor 0.0.1 depends on cbpi>=4.0.0.34
my CBPI4 version is 4.0.0.34

**Comment by hurra** [comment]
Hi,

can you describe what you did to get this error?

Are you trying to install both versions in parallel?

- Lorenz

E: Ahh, it's in the title

**Comment by hurra** [comment]
How did you install cbpi?
Maybe pip is confused, because on pypi there is only 4.0.0.28 right now?

**Comment by Pumba1970** [comment]
I did the installation discribed in https://hobbybrauer.de/forum/viewtopic.php?t=27386

sudo apt-get update && sudo apt-get upgrade # OS erstmal updaten

cd /home/pi

sudo apt-get install git #git wird benötigt um das Repo überhaupt clonen zu können
git clone https://github.com/Manuel83/craftbeerpi4 # Cloned das Repo in /home/pi/craftbeerpi4

cd craftbeerpi4/

sudo apt-get install python3-venv # Depencies für die Erstellung des Virtual Env´s
python3 -m venv py3 # Virtual Env erstellen, das ist immer zu empfehlen um irgendwelcher Depency fuckery aus dem weg zu gehen :-)

sudo apt-get install python3-dev # Wird für den Build Prozess benötigt
sudo apt-get install libatlas-base-dev # Depency für Numpy
py3/bin/pip3 install -r requirements.txt # Depencies werden ins venv installiert
py3/bin/pip3 install RPi.GPIO # Das musste ich manuell nachinstallieren, fehlt in der requierements.txt

py3/bin/python3 run.py setup # Erstellt den config Ordner im aktuellen Verzeichnis "Man sollte ja immernoch in /home/pi/craftbeerpi4" sein

py3/bin/python3 run.py start # Startet den Server auf port 8000

Dann mit dem Browser auf http://Raspis-IP:8000 gehen. Dann sollte sich die cbpi4 Seite öffnen.

**Comment by Pumba1970** [comment]
ok I solved it.
I used this Manual.
https://openbrewing.gitbook.io/craftbeerpi4_support/master/server-installation
your plugin works thanks.
